In [10]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [11]:
x = np.ones(3)
x

array([1., 1., 1.])

## Q#2: Create y array with elements equal to 0.

In [12]:
y = np.zeros(3)

## Q#3: Add x and y arrays.

In [13]:
x + y

array([1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type)

In [21]:
print("x dimension = " , x.ndim)
print("x shape = " , x.shape)
print("x size = " , x.size)
print("x type = " , x.dtype)

x dimension =  1
x shape =  (3,)
x size =  3
x type =  float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [23]:
w = np.arange(11 , 17)
w.shape = (3 , 2)
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [50]:
z = np.arange(1 , 4)
z.shape = (3 , 1)
z

array([[1],
       [2],
       [3]])

## Q#7: Combine the arrays z and w in vertical way then save it in a new variable "newArray".

In [81]:
newArray = np.hstack((z , w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [82]:
for i in newArray.flat:
    print(i)

1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [83]:
newArray.transpose()

array([[ 1,  2,  3],
       [11, 13, 15],
       [12, 14, 16]])

## Q#10: Decrement all elements of "newArray" with 1.

In [84]:
newArray -= 1
newArray

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [85]:
print("biggest = " , newArray.max())
print("Smallest = " , newArray.min())

biggest =  15
Smallest =  0


## Q#12: Print the first row of "newArray" using indexing.

In [86]:
print(newArray[0])

[ 0 10 11]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [87]:
print(newArray[1][1])

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using Slicing.

In [88]:
print(newArray[:1 , 0:1])
print(newArray[1:2 , 2:3])

[[0]]
[[13]]


## Q#15: Change the shape of "newArray" to (9,1).

In [89]:
newArray.shape = (9 , 1)
newArray

array([[ 0],
       [10],
       [11],
       [ 1],
       [12],
       [13],
       [ 2],
       [14],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [60]:
newArray.shape = (3 , 2)

ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉